### ISSUE TITLE
"claim[...] and noclaim[...]" produces a query which doesn't work

### ISSUE THREAD

**Issue by 96187** [smalyshev/wdq2sparql#4]
I tried to convert `claim[31:577] and noclaim[361:28892]` to SPARQL. The query it gave is:

```
prefix wdt: <http://www.wikidata.org/prop/direct/>
prefix entity: <http://www.wikidata.org/entity/>
SELECT ?item WHERE {
  ?item wdt:P31 entity:Q577 .
  OPTIONAL { ?item wdt:P361 entity:Q28892 }
  FILTER(!bound(entity:Q28892))
}
```

but if I click "Run this query!", it doesn't work, it gives an error about a malformed query:

```
ERROR: SPARQL-QUERY: queryStr=prefix wdt: 
prefix entity: 
SELECT ?item WHERE {
  ?item wdt:P31 entity:Q577 .
  OPTIONAL { ?item wdt:P361 entity:Q28892 }
  FILTER(!bound(entity:Q28892))
}
java.util.concurrent.ExecutionException: org.openrdf.query.MalformedQueryException: Encountered "  "entity:Q28892 "" at line 6, column 17.
Was expecting one of:
     ...
     ...

    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:281)
    at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:636)
    at com.bigdata.rdf.sail.webapp.QueryServlet.doGet(QueryServlet.java:278)
    at com.bigdata.rdf.sail.webapp.RESTServlet.doGet(RESTServlet.java:219)
    at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doGet(MultiTenancyServlet.java:214)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.openrdf.query.MalformedQueryException: Encountered "  "entity:Q28892 "" at line 6, column 17.
Was expecting one of:
     ...
     ...

    at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:459)
    at com.bigdata.rdf.sail.webapp.BigdataRDFContext.getQueryTask(BigdataRDFContext.java:2393)
    at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:713)
    at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:653)
    at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    ... 1 more
Caused by: com.bigdata.rdf.sail.sparql.ast.ParseException: Encountered "  "entity:Q28892 "" at line 6, column 17.
Was expecting one of:
     ...
     ...

    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.generateParseException(SyntaxTreeBuilder.java:9625)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.jj_consume_token(SyntaxTreeBuilder.java:9492)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Var(SyntaxTreeBuilder.java:3839)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Bound(SyntaxTreeBuilder.java:6542)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BuiltInCall(SyntaxTreeBuilder.java:5012)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.PrimaryExpression(SyntaxTreeBuilder.java:4531)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.UnaryExpression(SyntaxTreeBuilder.java:4319)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.MultiplicativeExpression(SyntaxTreeBuilder.java:4258)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.AdditiveExpression(SyntaxTreeBuilder.java:4164)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.NumericExpression(SyntaxTreeBuilder.java:4160)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.RelationalExpression(SyntaxTreeBuilder.java:3988)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ValueLogical(SyntaxTreeBuilder.java:3984)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalAndExpression(SyntaxTreeBuilder.java:3948)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalOrExpression(SyntaxTreeBuilder.java:3912)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Expression(SyntaxTreeBuilder.java:3908)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BrackettedExpression(SyntaxTreeBuilder.java:5005)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Constraint(SyntaxTreeBuilder.java:2546)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Filter(SyntaxTreeBuilder.java:2535)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.FilterOrBind(SyntaxTreeBuilder.java:2218)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BasicGraphPattern(SyntaxTreeBuilder.java:2134)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2007)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2029)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1942)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.WhereClause(SyntaxTreeBuilder.java:986)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.SelectQuery(SyntaxTreeBuilder.java:350)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Query(SyntaxTreeBuilder.java:301)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.QueryContainer(SyntaxTreeBuilder.java:189)
    at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.parseQuery(SyntaxTreeBuilder.java:32)
    at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:361)
    ... 8 more
```

**Comment by smalyshev** [comment]
Yes, that's a bug. Will fix soon.

**Comment by smalyshev** [comment]
Should be fixed now.
